# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'BinartOCPlotView', :git => 'https://github.com/fallending/BinartOCPlotView-iOS.git', :tag => '0.1.2'
  
  pod 'BinartOCStickerKeyboard', :path => '../'
  pod 'BinartOCLayout', :path => '../'
  pod 'BinartSwiftInputBar', :path => '../'

end
